### ISSUE TITLE
Ver detalles de todo

### ISSUE THREAD

**Issue by pabloHoc** [Ada-Online-2da-Gen/Todo-App#41]
**Descripción**

Como usuaria quiero poder ver los detalles de un todo en específico, así no se sobrecarga la pantalla principal de información extra que no es tan relevante, y puedo inspeccionar con detenimiento el que me interesa.

**Criterios de aceptación**

- Cuando la usuaria hace click en un todo, se debe abrir una ventana con los detalles del todo.
- Cuando la usuaria, estando la ventana de detalles abierta, hace click en el ícono de cerrar, esta debe cerrarse.
- Cuando la usuaria, estando la ventana de detalles abierta, hace click en el overlay fondo de la ventana, esta debe cerrarse.
- La ventana debe mostrar toda la información del todo correspondiente que hasta el momento: nombre, estado, fecha de creación, etiquetas, etc (las que no estén desarrolladas hasta el momento no deben implementarse todavía).

**Comment by pabloHoc** [comment]
Pueden tomar de referencia el comportamiento de Trello al hacer click en un todo.

**Comment by pabloHoc** [comment]
Ver issue #47 al respecto

**Comment by telemaca** [comment]
Pablo, consulta. Ahí decís que el click debe ser en el todo y no en el título, porque haciendo click en el ttítulo, este se edita. ¿Esa funcionalidad la tenemos que agregar? Porque en el issue de editar todo solo decía que se podía editar cliqueando el ícono de editar, no hacienco click en el título.

**Comment by pabloHoc** [comment]
Tenés razón! Se me mezclaron los tantos. Mejor entonces por ahora no, cualquier cosa después agregamos un issue.
